### ISSUE TITLE
Admin panel for Swiggy app

### ISSUE THREAD

**Issue by amarshaw** [vinothvino42/SwiggyUI#1]
Can you also share the admin panel for Swiggy app as well

**Comment by vinothvino42** [comment]
Sorry, Currently I'm not interested to do any admin panel work. I just have done this UI for learning purposes. I'll update this app's profile section and responsiveness of the app in the upcoming weeks.

**Comment by amarshaw** [comment]
Great, and your work is awesome, but only concern if some one use this app, how he/she can manage his/her product.

**Comment by vinothvino42** [comment]
Thank you so much! @amarshaw. They can use some code snippets of this project. It's just a UI Clone project, no functionality. They want to do everything manually.

**Comment by arindammitra06** [comment]
Really Nice Project.. I wish I could use this UI to migrate our Native Android project to Flutter... Thanks Again...

**Comment by vinothvino42** [comment]
> Really Nice Project.. I wish I could use this UI to migrate our Native Android project to Flutter... Thanks Again...

Thank you! Just now I updated the project to support flutter v2.0. Check out the latest code.
